insert into User (username, password, name) values ('rajeshja', 'rajeshja', 'Rajesh Advani')
insert into User (username, password, name) values ('demo', 'demo', 'Demo User')
insert into Simple (id, name, description) values (1, 'Data one', 'Junk data here')
insert into Simple (id, name, description) values (2, 'Data two', 'Junk data here')
insert into Simple (id, name, description) values (3, 'Data three', 'Junk data here')
insert into Simple (id, name, description) values (4, 'Data four', 'Junk data here')
insert into Simple (id, name, description) values (5, 'Data five', 'Junk data here')
insert into Simple (id, name, description) values (6, 'Data six', 'Junk data here')
